### ISSUE TITLE
Maverick seems to not filter out known benign variants

### ISSUE THREAD

**Issue by Qmphcm5l** [ZuchnerLab/Maverick#11]
Hi, I want to use maverick to hunt for genes that cause auto inflammatory diseases. For this I got a bunch of whole genome variant vcfs of patients with those diseases. When I run my vcf files both with the maverick lite and full mode, my final scores contain a bunch of variants that are known benign variants on gnomad like CCDC66 3-56557250-T-TGGGGTAAGCA.
This seems confusing to me as gnomad reference files are available for maverick.
The input vcfs have been properly prepared for the use with annovar and the coordinates of the out put files line up with the coordinates of the input vcfs.

**Comment by Qmphcm5l** [comment]
Update, it seems like after having a look at the gnomad211_grch38_exons_af.txt that those variants are not present in that database. Is there any way to work around this so that these variants are filtered out and i only get my unique mutations?

**Comment by mdanzi** [comment]
Hello, apologies for my slow reply here! I clearly missed the notification that this issue was posted. 

You could absolutely swap in gnomad4 allele frequencies or anything like that and use them in place of the gnomad2.1.1 ones that I use currently, but that is not something that I plan to do and test out in the near future. The safest thing to do would simply be to run Maverick as-is and then create your own post-processing step which can filter using allele frequencies from gnomad4 or other sources as you see fit.
